### ISSUE TITLE
Correct Google Fonts Links

### ISSUE THREAD

**Issue by jesse-stew** [WebDevAndDesign/blocBox#1]
Right now in your `<head>`s, you're pulling in Lato & Varela Round instead of Fredoka One & Avenir (which you're using in the CSS).

**Comment by WebDevAndDesign** [comment]
I could not find a free version of Avenir so I switch the body copy to Lato. The website now has Lato for body and Fredoka One for headers.

**Comment by WebDevAndDesign** [comment]
Wuh ohhhhh... turns out that hack didn't work so well. Do you know how I could best go about including Avenir?

**Comment by WebDevAndDesign** [comment]
Correct font issue. Avenir replaced with Lato.
