### ISSUE TITLE
Dashboard Navbar fonts thin in Safari

### ISSUE THREAD

**Issue by WebDevAndDesign** [WebDevAndDesign/blocBox#4]
The fonts are super thin in the navbar of the dashboard when viewed on Safari.

**Comment by jesse-stew** [comment]
They're set to `font-weight: 100`, so they will be super thin. Look at the styles for `.left-nav .items ul li a` starting line 503 in your CSS.

I would change the font-weight to 400.

**Comment by WebDevAndDesign** [comment]
Thanks! I completed your directions and pushed to GitHub, but am not seeing the changes. The changes are on the `gh-pages` branch. Do you know if when we view the website from GitHub _if_ the page we see is from `gh-pages` branch or `master` branch?

**Comment by WebDevAndDesign** [comment]
The font width appears to be 400 now :).

**Comment by jesse-stew** [comment]
`gh-pages` branch, just might take a few minutes to update.

I think you can close out this issue since it's resolved! 🚀
